"""ORM model registry for Alembic and application imports.

Importing this package registers all mapped tables on Base.metadata.
"""

from app.db.models.affiliation import (
    AffiliationBeneficiary,
    AffiliationCategoryHistory,
    AffiliationEmployer,
    AffiliationLookupLog,
    AffiliationRecord,
)
from app.db.models.audit import (
    AuditEvent,
    IntegrationEvent,
    OutboxEvent,
    SecurityEvent,
)
from app.db.models.commercial import (
    Advisor,
    AdvisorAssignment,
    AdvisorQueue,
    Appointment,
    CommercialOutcome,
    FollowUpTask,
    RegulatoryPeriod,
    RegulatorySnapshot,
)
from app.db.models.conversations import (
    ConversationEvent,
    ConversationMessage,
    ConversationMetrics,
    ConversationSession,
    ToolExecution,
)
from app.db.models.core import (
    AlgorithmVersion,
    AppSetting,
    Channel,
    DataSource,
    FeatureFlag,
)
from app.db.models.housing import (
    Project,
    ProjectAlias,
    ProjectAsset,
    ProjectAvailability,
    ProjectHistoricalProfile,
    ProjectLocation,
    ProjectPrice,
    ProjectProfileDistribution,
    ProjectStage,
)
from app.db.models.identity import (
    Consent,
    ContactPoint,
    IdentityLookupEvent,
    IdentityMatch,
    Person,
    PersonIdentifier,
)
from app.db.models.ingestion import (
    EntityMatchCandidate,
    ImportBatch,
    NormalizationIssue,
    NormalizedBuyerRecord,
    RawRecord,
    SeedExecution,
)
from app.db.models.leads import (
    Lead,
    LeadEvent,
    LeadFieldMetadata,
    LeadProfile,
    LeadProfileChange,
    LeadSourceDetails,
    LeadStatusHistory,
)
from app.db.models.qualification import (
    Assessment,
    AssessmentFactor,
    LeadAnswer,
    NutritionAction,
    NutritionPlan,
    QuestionDefinition,
)
from app.db.models.recommendations import (
    RecommendationFactor,
    RecommendationFeedback,
    RecommendationItem,
    RecommendationRun,
)

__all__ = [
    "Advisor",
    "AdvisorAssignment",
    "AdvisorQueue",
    "AffiliationBeneficiary",
    "AffiliationCategoryHistory",
    "AffiliationEmployer",
    "AffiliationLookupLog",
    "AffiliationRecord",
    "AlgorithmVersion",
    "AppSetting",
    "Appointment",
    "Assessment",
    "AssessmentFactor",
    "AuditEvent",
    "Channel",
    "CommercialOutcome",
    "Consent",
    "ContactPoint",
    "ConversationEvent",
    "ConversationMessage",
    "ConversationMetrics",
    "ConversationSession",
    "DataSource",
    "EntityMatchCandidate",
    "FeatureFlag",
    "FollowUpTask",
    "IdentityLookupEvent",
    "IdentityMatch",
    "ImportBatch",
    "IntegrationEvent",
    "Lead",
    "LeadAnswer",
    "LeadEvent",
    "LeadFieldMetadata",
    "LeadProfile",
    "LeadProfileChange",
    "LeadSourceDetails",
    "LeadStatusHistory",
    "NormalizationIssue",
    "NormalizedBuyerRecord",
    "NutritionAction",
    "NutritionPlan",
    "OutboxEvent",
    "Person",
    "PersonIdentifier",
    "Project",
    "ProjectAlias",
    "ProjectAsset",
    "ProjectAvailability",
    "ProjectHistoricalProfile",
    "ProjectLocation",
    "ProjectPrice",
    "ProjectProfileDistribution",
    "ProjectStage",
    "QuestionDefinition",
    "RawRecord",
    "RecommendationFactor",
    "RecommendationFeedback",
    "RecommendationItem",
    "RecommendationRun",
    "RegulatoryPeriod",
    "RegulatorySnapshot",
    "SecurityEvent",
    "SeedExecution",
    "ToolExecution",
]
