"""Generate a small fictional buyers CSV matching the hackathon export schema.

Usage:
    python scripts/generate_mock_buyers.py
    python scripts/generate_mock_buyers.py --output data/mock/mock_buyers.csv
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

COLUMNS = [
    "NOMBRE_PROYECTO",
    "ETAPA",
    "FEC_OPCION",
    "FECHA_DESISTIMIENTO",
    "Entidad Financiera compra",
    "MEDIO",
    "VLR_VIVIENDA",
    "PERIODO",
    "PERIODO_AFILIADO",
    "SEGMENTO_POBLACIONAL",
    "CATEGORIA",
    "RANGO_EDAD",
    "NO_GRUPO_FAMILAR",
    "NO_BENEFICIARIOS_CUOTA_MONETARIA",
    "PIRAMIDE_NUEVA",
    "EMPRESA_FOCO",
]

# Housing values are stored in the same inflated export format as the real file
# (prepare_data scales by /10000). Example: 185_000_000 COP → 1,850,000,000,000
def _vlr(cop: int) -> str:
    inflated = cop * 10_000
    return f"{inflated:,}"


# Fictional rows only. No real personal data.
MOCK_ROWS: list[dict[str, str]] = [
    {
        "NOMBRE_PROYECTO": "Agrupación De Vivienda Monguí",
        "ETAPA": "ETAPA 1",
        "FEC_OPCION": "3/12/2024",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Banco",
        "MEDIO": "Referido",
        "VLR_VIVIENDA": _vlr(195_000_000),
        "PERIODO": "2024-3",
        "PERIODO_AFILIADO": "2024-3",
        "SEGMENTO_POBLACIONAL": "KAPPA",
        "CATEGORIA": "OMEGA",
        "RANGO_EDAD": "20 a 35 años",
        "NO_GRUPO_FAMILAR": "2",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "1",
        "PIRAMIDE_NUEVA": "TAU",
        "EMPRESA_FOCO": "X",
    },
    {
        "NOMBRE_PROYECTO": "Agrupación De Vivienda La Macarena",
        "ETAPA": "ETAPA 2",
        "FEC_OPCION": "5/20/2024",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Colsubsidio",
        "MEDIO": "Valla",
        "VLR_VIVIENDA": _vlr(168_000_000),
        "PERIODO": "2024-5",
        "PERIODO_AFILIADO": "2024-5",
        "SEGMENTO_POBLACIONAL": "SIGMA",
        "CATEGORIA": "OMEGA",
        "RANGO_EDAD": "36 a 45 años",
        "NO_GRUPO_FAMILAR": "3",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "2",
        "PIRAMIDE_NUEVA": "GAMMA",
        "EMPRESA_FOCO": "",
    },
    {
        "NOMBRE_PROYECTO": "INARI",
        "ETAPA": "ETAPA 1",
        "FEC_OPCION": "1/18/2025",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Banco",
        "MEDIO": "Redes Sociales",
        "VLR_VIVIENDA": _vlr(320_000_000),
        "PERIODO": "2025-1",
        "PERIODO_AFILIADO": "2025-1",
        "SEGMENTO_POBLACIONAL": "NU",
        "CATEGORIA": "ETA",
        "RANGO_EDAD": "20 a 35 años",
        "NO_GRUPO_FAMILAR": "1",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "0",
        "PIRAMIDE_NUEVA": "RHO",
        "EMPRESA_FOCO": "X",
    },
    {
        "NOMBRE_PROYECTO": "Versalles",
        "ETAPA": "ETAPA 3",
        "FEC_OPCION": "8/4/2024",
        "FECHA_DESISTIMIENTO": "Si",
        "Entidad Financiera compra": "Banco",
        "MEDIO": "Sin Informacion",
        "VLR_VIVIENDA": _vlr(210_000_000),
        "PERIODO": "2024-8",
        "PERIODO_AFILIADO": "",
        "SEGMENTO_POBLACIONAL": "PI",
        "CATEGORIA": "CHI",
        "RANGO_EDAD": "",
        "NO_GRUPO_FAMILAR": "",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "",
        "PIRAMIDE_NUEVA": "XI",
        "EMPRESA_FOCO": "",
    },
    {
        "NOMBRE_PROYECTO": "Los Nogales",
        "ETAPA": "ETAPA 1",
        "FEC_OPCION": "11/2/2024",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Colsubsidio",
        "MEDIO": "Ferias empresariales",
        "VLR_VIVIENDA": _vlr(410_000_000),
        "PERIODO": "2024-11",
        "PERIODO_AFILIADO": "2024-11",
        "SEGMENTO_POBLACIONAL": "SIGMA",
        "CATEGORIA": "TAU",
        "RANGO_EDAD": "46 a 55 años",
        "NO_GRUPO_FAMILAR": "2",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "1",
        "PIRAMIDE_NUEVA": "ALPHA",
        "EMPRESA_FOCO": "X",
    },
    {
        "NOMBRE_PROYECTO": "Agrupacion De Vivienda Bosque De Arrayan",
        "ETAPA": "ETAPA 3",
        "FEC_OPCION": "2/14/2024",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Banco",
        "MEDIO": "Banderas y/o señalización",
        "VLR_VIVIENDA": _vlr(177_000_000),
        "PERIODO": "2024-2",
        "PERIODO_AFILIADO": "2024-2",
        "SEGMENTO_POBLACIONAL": "KAPPA",
        "CATEGORIA": "OMEGA",
        "RANGO_EDAD": "20 - 35 años",
        "NO_GRUPO_FAMILAR": "1",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "1",
        "PIRAMIDE_NUEVA": "NU",
        "EMPRESA_FOCO": "",
    },
    {
        "NOMBRE_PROYECTO": "ARAUCARIA",
        "ETAPA": "ETAPA 2",
        "FEC_OPCION": "6/30/2024",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Contado",
        "MEDIO": "Página web",
        "VLR_VIVIENDA": _vlr(355_000_000),
        "PERIODO": "2024-6",
        "PERIODO_AFILIADO": "2024-6",
        "SEGMENTO_POBLACIONAL": "NU",
        "CATEGORIA": "OMEGA",
        "RANGO_EDAD": "36 - 45 años",
        "NO_GRUPO_FAMILAR": "4",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "2",
        "PIRAMIDE_NUEVA": "GAMMA",
        "EMPRESA_FOCO": "",
    },
    {
        "NOMBRE_PROYECTO": "La Arboleda",
        "ETAPA": "ETAPA 1",
        "FEC_OPCION": "9/9/2024",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Banco",
        "MEDIO": "Whatsapp",
        "VLR_VIVIENDA": _vlr(280_000_000),
        "PERIODO": "2024-9",
        "PERIODO_AFILIADO": "",
        "SEGMENTO_POBLACIONAL": "PI",
        "CATEGORIA": "CHI",
        "RANGO_EDAD": "",
        "NO_GRUPO_FAMILAR": "2",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "",
        "PIRAMIDE_NUEVA": "XI",
        "EMPRESA_FOCO": "",
    },
    {
        "NOMBRE_PROYECTO": "Agrupación De Vivienda Pamplona I",
        "ETAPA": "ETAPA 2",
        "FEC_OPCION": "4/22/2024",
        "FECHA_DESISTIMIENTO": "Si",
        "Entidad Financiera compra": "Colsubsidio",
        "MEDIO": "Sin Informacion",
        "VLR_VIVIENDA": _vlr(190_000_000),
        "PERIODO": "2024-4",
        "PERIODO_AFILIADO": "2024-4",
        "SEGMENTO_POBLACIONAL": "KAPPA",
        "CATEGORIA": "ETA",
        "RANGO_EDAD": "20 a 35 años",
        "NO_GRUPO_FAMILAR": "",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "0",
        "PIRAMIDE_NUEVA": "ZETA",
        "EMPRESA_FOCO": "",
    },
    {
        "NOMBRE_PROYECTO": "Zarzal",
        "ETAPA": "ETAPA 1",
        "FEC_OPCION": "12/1/2024",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Banco",
        "MEDIO": "Referido Alcaldía",
        "VLR_VIVIENDA": _vlr(165_000_000),
        "PERIODO": "2024-12",
        "PERIODO_AFILIADO": "2024-12",
        "SEGMENTO_POBLACIONAL": "SIGMA",
        "CATEGORIA": "OMEGA",
        "RANGO_EDAD": "Mayor de 55 años",
        "NO_GRUPO_FAMILAR": "1",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "1",
        "PIRAMIDE_NUEVA": "RHO",
        "EMPRESA_FOCO": "X",
    },
    {
        "NOMBRE_PROYECTO": "AGRUPACIÓN DE VIVIENDA SAMÁN",
        "ETAPA": "ETAPA 1",
        "FEC_OPCION": "7/15/2024",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Banco",
        "MEDIO": "Activación",
        "VLR_VIVIENDA": _vlr(172_000_000),
        "PERIODO": "2024-7",
        "PERIODO_AFILIADO": "2024-7",
        "SEGMENTO_POBLACIONAL": "KAPPA",
        "CATEGORIA": "OMEGA",
        "RANGO_EDAD": "36 a 45 años",
        "NO_GRUPO_FAMILAR": "2",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "1",
        "PIRAMIDE_NUEVA": "TAU",
        "EMPRESA_FOCO": "",
    },
    {
        "NOMBRE_PROYECTO": "Agrupacion De Vivienda Payande",
        "ETAPA": "ETAPA 2",
        "FEC_OPCION": "10/8/2024",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Colsubsidio",
        "MEDIO": "Contact Center",
        "VLR_VIVIENDA": _vlr(158_000_000),
        "PERIODO": "2024-10",
        "PERIODO_AFILIADO": "2024-10",
        "SEGMENTO_POBLACIONAL": "NU",
        "CATEGORIA": "ETA",
        "RANGO_EDAD": "20 a 35 años",
        "NO_GRUPO_FAMILAR": "0",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "0",
        "PIRAMIDE_NUEVA": "IOTA",
        "EMPRESA_FOCO": "",
    },
    {
        "NOMBRE_PROYECTO": "CONJUNTO RESIDENCIAL VIBO ONCE",
        "ETAPA": "ETAPA 1",
        "FEC_OPCION": "2/28/2025",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Banco",
        "MEDIO": "Redes Sociales",
        "VLR_VIVIENDA": _vlr(390_000_000),
        "PERIODO": "2025-2",
        "PERIODO_AFILIADO": "2025-2",
        "SEGMENTO_POBLACIONAL": "SIGMA",
        "CATEGORIA": "TAU",
        "RANGO_EDAD": "36 a 45 años",
        "NO_GRUPO_FAMILAR": "3",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "2",
        "PIRAMIDE_NUEVA": "ALPHA",
        "EMPRESA_FOCO": "X",
    },
    {
        "NOMBRE_PROYECTO": "Proyecto Karakalí",
        "ETAPA": "ETAPA 1",
        "FEC_OPCION": "3/5/2025",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Banco",
        "MEDIO": "Valla",
        "VLR_VIVIENDA": _vlr(245_000_000),
        "PERIODO": "2025-3",
        "PERIODO_AFILIADO": "",
        "SEGMENTO_POBLACIONAL": "PI",
        "CATEGORIA": "CHI",
        "RANGO_EDAD": "",
        "NO_GRUPO_FAMILAR": "1",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "",
        "PIRAMIDE_NUEVA": "XI",
        "EMPRESA_FOCO": "",
    },
    {
        "NOMBRE_PROYECTO": "ABETO",
        "ETAPA": "ETAPA 3",
        "FEC_OPCION": "1/9/2024",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Colsubsidio",
        "MEDIO": "Referido",
        "VLR_VIVIENDA": _vlr(365_000_000),
        "PERIODO": "2024-1",
        "PERIODO_AFILIADO": "2024-1",
        "SEGMENTO_POBLACIONAL": "NU",
        "CATEGORIA": "OMEGA",
        "RANGO_EDAD": "46 a 55 años",
        "NO_GRUPO_FAMILAR": "2",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "1",
        "PIRAMIDE_NUEVA": "GAMMA",
        "EMPRESA_FOCO": "",
    },
    {
        "NOMBRE_PROYECTO": "VERDE ESPERANZA EL DORADO",
        "ETAPA": "ETAPA 2",
        "FEC_OPCION": "5/11/2024",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Banco",
        "MEDIO": "Ferias empresariales",
        "VLR_VIVIENDA": _vlr(188_000_000),
        "PERIODO": "2024-5",
        "PERIODO_AFILIADO": "2024-5",
        "SEGMENTO_POBLACIONAL": "KAPPA",
        "CATEGORIA": "OMEGA",
        "RANGO_EDAD": "20 a 35 años",
        "NO_GRUPO_FAMILAR": "2",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "1",
        "PIRAMIDE_NUEVA": "TAU",
        "EMPRESA_FOCO": "X",
    },
    {
        "NOMBRE_PROYECTO": "Agrupacion De Vivienda Reserva De Guayacan",
        "ETAPA": "ETAPA 1",
        "FEC_OPCION": "8/19/2024",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Banco",
        "MEDIO": "Banderas y/o señalización",
        "VLR_VIVIENDA": _vlr(236_000_000),
        "PERIODO": "2024-8",
        "PERIODO_AFILIADO": "2024-8",
        "SEGMENTO_POBLACIONAL": "SIGMA",
        "CATEGORIA": "ETA",
        "RANGO_EDAD": "36 a 45 años",
        "NO_GRUPO_FAMILAR": "1",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "1",
        "PIRAMIDE_NUEVA": "RHO",
        "EMPRESA_FOCO": "",
    },
    {
        "NOMBRE_PROYECTO": "AGRUPACIÓN DE VIVIENDA BOSQUE DE TURPIAL",
        "ETAPA": "ETAPA 2",
        "FEC_OPCION": "9/27/2024",
        "FECHA_DESISTIMIENTO": "Si",
        "Entidad Financiera compra": "Colsubsidio",
        "MEDIO": "Sin Informacion",
        "VLR_VIVIENDA": _vlr(175_000_000),
        "PERIODO": "2024-9",
        "PERIODO_AFILIADO": "2024-9",
        "SEGMENTO_POBLACIONAL": "KAPPA",
        "CATEGORIA": "OMEGA",
        "RANGO_EDAD": "20 a 35 años",
        "NO_GRUPO_FAMILAR": "",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "0",
        "PIRAMIDE_NUEVA": "NU",
        "EMPRESA_FOCO": "",
    },
    {
        "NOMBRE_PROYECTO": "VILLA MERCEDES EL DORADO",
        "ETAPA": "ETAPA 1",
        "FEC_OPCION": "11/30/2024",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Banco",
        "MEDIO": "Whatsapp",
        "VLR_VIVIENDA": _vlr(205_000_000),
        "PERIODO": "2024-11",
        "PERIODO_AFILIADO": "",
        "SEGMENTO_POBLACIONAL": "PI",
        "CATEGORIA": "CHI",
        "RANGO_EDAD": "",
        "NO_GRUPO_FAMILAR": "3",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "",
        "PIRAMIDE_NUEVA": "XI",
        "EMPRESA_FOCO": "",
    },
    {
        "NOMBRE_PROYECTO": "Agrupación De Vivienda Monguí",
        "ETAPA": "ETAPA 2",
        "FEC_OPCION": "6/6/2025",
        "FECHA_DESISTIMIENTO": "No",
        "Entidad Financiera compra": "Colsubsidio",
        "MEDIO": "Referido",
        "VLR_VIVIENDA": _vlr(202_000_000),
        "PERIODO": "2025-6",
        "PERIODO_AFILIADO": "2025-6",
        "SEGMENTO_POBLACIONAL": "KAPPA",
        "CATEGORIA": "OMEGA",
        "RANGO_EDAD": "Menor de 19 años",
        "NO_GRUPO_FAMILAR": "",
        "NO_BENEFICIARIOS_CUOTA_MONETARIA": "0",
        "PIRAMIDE_NUEVA": "IOTA",
        "EMPRESA_FOCO": "",
    },
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Genera CSV ficticio de compradores con el esquema del reto.",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="data/mock/mock_buyers.csv",
        help="Ruta de salida (default: data/mock/mock_buyers.csv)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = Path(args.output)
    if not output.is_absolute():
        output = ROOT / output
    output.parent.mkdir(parents=True, exist_ok=True)

    with output.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=COLUMNS)
        writer.writeheader()
        for row in MOCK_ROWS:
            writer.writerow({column: row.get(column, "") for column in COLUMNS})

    affiliated = sum(1 for row in MOCK_ROWS if row.get("PERIODO_AFILIADO"))
    desisted = sum(1 for row in MOCK_ROWS if row.get("FECHA_DESISTIMIENTO") == "Si")
    print(f"Generado: {output}")
    print(f"Filas: {len(MOCK_ROWS)} | Afiliados: {affiliated} | Desistimientos: {desisted}")
    print("Datos 100% ficticios; no contienen información personal real.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
