export type QuestionFieldType = 'boolean' | 'currency' | 'integer' | 'text' | 'enum' | 'consent' | 'confirmation'
export type DocumentType = 'CC' | 'CE' | 'PA' | string
export type AffiliationCategory = 'A' | 'B' | 'C' | 'D'
export type ConfidenceLevel = 'low' | 'medium' | 'high'
export type LeadStatus = string

export interface NextQuestion { field: string; question: string; type: QuestionFieldType; required: boolean; reason: string; confirmation_required?: boolean; current_value?: unknown; source?: string | null }
export interface NextQuestionResponse { completed: boolean; next_question?: NextQuestion | null }
export interface IdentityLookupResponse { match_status: string; known_lead: boolean; identity_verified: boolean; profile_source: string; prefilled_profile: Record<string, unknown>; prefilled_fields: string[]; fields_to_confirm: string[]; consent_required: boolean; demo_mode: boolean }
export interface FieldProvenance { source: string; confirmed: boolean; requires_confirmation: boolean; updated_at?: string | null; previous_value?: unknown }
export interface LeadResponse {
  id: string; nombre?: string | null; telefono?: string | null; correo?: string | null; canal_origen: string; consentimiento?: boolean | null; afiliado?: boolean | null; afiliacion_confirmada: boolean; categoria_afiliacion?: AffiliationCategory | null; empresa?: string | null; salario_mensual?: number | null; ingreso_hogar?: number | null; ahorro?: number | null; obligaciones_mensuales?: number | null; tiene_vivienda?: boolean | null; personas_hogar?: number | null; personas_a_cargo?: number | null; beneficiarios_registrados?: number | null; situacion_crediticia?: string | null; ubicacion_actual?: string | null; ubicacion_deseada?: string | null; plazo_compra?: string | null; proyecto_interes?: string | null; preferencias?: string[] | null; document_type?: string | null; document_number?: string | null; known_lead?: boolean; identity_status?: string | null; identity_verified?: boolean; profile_source?: string | null; prefilled_fields?: string[]; fields_to_confirm?: string[]; field_metadata?: Record<string, FieldProvenance>; data_consent?: boolean | null; data_consent_at?: string | null; demo_mode?: boolean; estado_lead?: LeadStatus; status?: LeadStatus; fecha_creacion?: string; fecha_actualizacion?: string; created_at?: string; updated_at?: string; [key: string]: unknown
}
export interface ProjectRecommendation { project_id: string; project_name: string; canonical_project_id: string; rank: number; compatibility_score: number; confidence: ConfidenceLevel; matched_factors?: { factor: string; message: string; contribution: number }[]; warnings?: string[]; unavailable_factors?: string[]; brochure_url?: string | null; tour_360_url?: string | null; municipio?: string | null; departamento?: string | null; etapa?: string | null; historical_profile_available?: boolean; aliases?: string[]; metadata?: Record<string, unknown> }
export interface RecommendationResponse { lead_id: string; recommendation_status: string; evaluated_projects: number; recommended_projects: ProjectRecommendation[]; [key: string]: unknown }
export interface ReadinessResponse { lead_id: string; readiness_score: number; confidence: ConfidenceLevel; status: string; complete_fields: string[]; missing_fields: string[]; positive_factors: string[]; gaps: string[]; next_action: string; warnings: string[]; disclaimer: string }
export interface AdvisorSummaryResponse { lead_id: string; headline: string; basic_data: Record<string, string | null>; affiliation: Record<string, unknown>; financial_profile: Record<string, unknown>; household: Record<string, unknown>; readiness: Record<string, unknown>; gaps: string[]; fields_to_confirm: string[]; recommended_projects: Record<string, unknown>[]; recommendation_warning?: string | null; identity_context?: Record<string, unknown> | null; confirmed_fields: string[]; field_sources: Record<string, unknown>; next_action: string; disclaimer: string }
export interface DemoIdentityItem { name: string; document_number: string; document_type: string; scenario: string }
export interface LeadFromIdentityResponse { lead: LeadResponse; identity_context: Record<string, unknown>; next_question?: NextQuestion | null; demo_mode: boolean }
export type LeadUpdate = Partial<{ nombre: string | null; telefono: string | null; correo: string | null; consentimiento: boolean | null; afiliado: boolean | null; afiliacion_confirmada: boolean | null; categoria_afiliacion: AffiliationCategory | null; empresa: string | null; salario_mensual: number | null; ingreso_hogar: number | null; ahorro: number | null; obligaciones_mensuales: number | null; tiene_vivienda: boolean | null; personas_hogar: number | null; personas_a_cargo: number | null; beneficiarios_registrados: number | null; situacion_crediticia: string | null; ubicacion_actual: string | null; ubicacion_deseada: string | null; plazo_compra: string | null; proyecto_interes: string | null; preferencias: string[] | null; data_consent: boolean | null; document_type: string | null; document_number: string | null; estado_lead: LeadStatus | null; canal_origen: string | null }>
